### ISSUE TITLE
Admin View Interface implementation 

### ISSUE THREAD

**Issue by peacendlovu** [Software-Design-2022/DFMPC-Student-Placement-System#26]
## Manage Records in the Database
- Manage users
- Change emergency Protocols
## Super User (separate system)
 - Website, a menu showing tables 

To collaborate with @peacendlovu 

![image](https://user-images.githubusercontent.com/53468145/163568322-141077a9-ebdf-409d-98e8-7bdbecbf4096.png)

![image](https://user-images.githubusercontent.com/53468145/163978216-60289b75-ec72-4d1c-9ea1-92ac6efed722.png)

**Comment by nokuthabam** [comment]
### Admin website created. 

- The website allows an admin user to login. 
- The admin is able to make changes to the USERS table by adding users, editing existing user information and deleting users.
- The admin is able to make changes to the PROTOCOLS table by adding or deleting protocols.
